### ISSUE TITLE
How to add more languages?

### ISSUE THREAD

**Issue by daihuaye** [wooorm/udhr#2]
Hi,

I like your Franc library and it's magical. :)
I am wondering how to add more languages since our project requirement are need few more. I think this is the right place to add more languages that are consumed by Franc, right?

Wondering do you have script to populate those html file in https://github.com/wooorm/udhr/tree/main/declaration? What are all the places to modify to add a language? 

Best and Thank you!

**Comment by daihuaye** [comment]
@wooorm Here are the three language I would like to add to the languages list, let me know if I could help to create pull request for them.
New Tai Lue:
https://www.unicode.org/charts/PDF/U1980.pdf

Tai Le:
https://www.unicode.org/charts/PDF/U1950.pdf

Mongolian (mon), which is different from Halh Mongolian (khk):
https://www.unicode.org/charts/PDF/U1800.pdf

**Comment by wooorm** [comment]
Hi!

There is indeed such a script, in the aptly named [`script/`](https://github.com/wooorm/udhr/tree/main/script) directory ;)

However, the scripts you link don’t have a corresponding [declaration of human rights](https://www.unicode.org/udhr/translations.html). See their [Contributing](https://www.unicode.org/udhr/contributing.html) section for how to help Unicode.
Once they’re transcribed, they can automatically be pulled into this project and franc.
